import { useRouter } from 'next/router'
import { useState } from 'react';
import { useEffect } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'


import { authorizeSpotify, getAccessToken, fetchProfile } from '@/utils/spotify';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [profile, setProfile] = useState<UserProfile | undefined>(undefined);
  const [error, setError] = useState<string>('');
  const router = useRouter();
  const { code } = router.query;

  useEffect(() => {
    const savedtoken = window.localStorage.getItem('spotify-token');
    if (savedtoken) {
      router.replace('/', undefined, { shallow: true });
      fetchProfile(savedtoken).then((profile) => {
        setProfile(profile);
      })
    } else if (code) {
      getAccessToken(code)
        .then((token) => {
          router.replace('/', undefined, { shallow: true });
          fetchProfile(token).then((profile) => {
            setProfile(profile);
          })
        })
        .catch((error) => {
          setError(error.error_description)
        })
    }
  }, [code]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button onClick={() => authorizeSpotify()}>
            Click to auth
          </button>
          { profile && <div>
            {/* <Image
              src={profile.images[0].url}
              alt="Picture of the author"
              width={500}
              height={500}
            /> */}
            { profile.display_name }
          </div> }
          { error && <div>{ error }</div> }
        </div>
      </main>
    </>
  )
}
